config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

devise_scope :user do
  authenticated :user do
    root 'users/sessions#show', as: "users"
  end
  unauthenticated :user do
    root 'welcome#index', as: :unauthenticated_root
  end

  resource :movies
  get 'movies/top_rated' => 'movies#top_rated'
  get 'movies/of_the_day' => 'movies#of_the_day'
  get 'movies/now_playing' => 'movies#now_playing'
  get 'movies/upcoming' => 'movies#upcoming'
  get 'movies/search' => 'movies#search'

  get '/about' => 'welcome#about'
end

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :users

  include HTTParty

  base_uri "https://api.themoviedb.org"

  def initialize
    @options = { query: { api_key: "14bcb6c3426d5e9a2bf0f8d393e9b38f" } }
  end

  def find_movies(input)
    @options[:query] = @options[:query].merge(query: input)
    self.class.get("/3/search/movie/", @options )
  end

  def top_rated_movies
    self.class.get("/3/movie/top_rated", @options)
  end

  def popular_movies
    self.class.get("/3/movie/popluar", @options)
  end

  def now_playing_movies
    self.class.get("/3/movie/now_playing", @options)
  end

  def upcoming_movies
    self.class.get("3/movie/upcoming", @options)
  end



end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :movies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
  end

  def create
    @movies = Movie.new.find_movies(params[:search])
  end

  def show
    @movies = Movie.new.find_movies(params[:search])
  end

  def top_rated
    @movies = Movie.new
    @movies = @movies.top_rated_movies
    render 'top_rated'
  end

  def of_the_day
    @movies = Movie.new.popular_movies
    render 'top_rated'
  end

  def now_playing
    @movies = Movie.new.now_playing_movies
    render 'top_rated'
  end

  def upcoming
    @movies = Movie.new.now_playing_movies
    render 'top_rated'
  end

  def search
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @user = User.new
    respond_to do |format|
      format.js
    end
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
#before_filter :configure_sign_in_params, only: [:create]

  #GET /resource/sign_in
  def new
    @user = User.new
    if request.xhr?
      respond_to do |format|
        format.js { render "new", resource: :resource }
      end
    end
  end

  #POST /resource/sign_in
  def create
    super
    puts "***********************************"
    puts "********** this is create *********"
    puts "***********************************"

    puts params
  end

  def show

  end
  # DELETE /resource/sign_out
  def destroy
    super
  end



  # protected
  #
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    # if !user_signed_in?
    #   redirect_to new_user_session_path
    # end
    # return
  end

  def about
    respond_to do |format|
    format.js
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/movies_helper.rb
module MoviesHelper

def poster_link(input)
  "http://image.tmdb.org/t/p/w154/" + input.to_s
end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Movies</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', "https://fonts.googleapis.com/css?family=Candal|Oxygen", media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "users/partials/navbar" %>
<% if notice || alert %>
  <!-- <span class="notice"><%= notice %></span>
  <span class="alert"><%= alert %></span> -->
<% end %>

<%= yield %>

</body>
</html>

app/views/movies/new.html.erb
hi

app/views/movies/of_the_day.html.erb
<%= @movies %>

app/views/movies/partials/_top_rated.html.erb
<%= @movies %>

app/views/movies/partials/index.html.erb
test

app/views/movies/show.html.erb
<%if @movies %>
  <% @movies["results"].each do |movie| %>
    <div class="container">
      <div class="poster col-md-6">
        <img src=<%= poster_link(movie["poster_path"]) %> />
      </div>
      <div class="info col-md-6">
        <div class="title">
          <em>Title:</em> <%= movie["title"]%>(<%= movie["original_title"] %>)
        </div>
        <p></p>
        <div class="overview">
          <em>Overview:</em>
          <% if movie["overview"] == "" %>
            n/a
          <% end %>
          <%= movie["overview"]%>
        </div>

      </div>

    </div>
  <% end %>
<% end %>

app/views/movies/top_rated.html.erb
<ol>
  <% @movies["results"].each do |movie| %>
    <li><%= movie["title"] %></li>
  <% end %>
</ol>

app/views/users/partials/_dashboard.html.erb
<div class="container border">
  <div class="row">
    <div class="col-md-3 border">Profile</div>
    <div class="col-md-6 border">Review
      <%= form_tag movies_path, :method => 'get' do %>
      <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
      </p>
      <% end %>

    </div>
    <div class="col-md-3 border">
      <ul>Top Ten
        <li><%= link_to "Top Rated Movies", movies_top_rated_path %></li>
        <li><%= link_to "Popular Movies of the Day", movies_of_the_day_path %></li>
        <li><%= link_to "Now Playing", movies_now_playing_path %></li>
        <li><%= link_to "Upcoming movies", movies_upcoming_path %></li>
      </ul>
      <p><%= link_to "Search", movies_search_path%></p>
    </div>
  </div>
</div>

<%= link_to "movies", movies_path %>

app/views/users/partials/_navbar.html.erb
  <nav class="navbar navbar-inverse">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed"
        data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" herf="#">MovieLover</a>
    </div>
    <div class="collapse navbar-collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to "Home", user_session_path%></li>
        <% end %>
        <% if !current_user %>
          <li><%= link_to "Signin", new_user_registration_path, class: "login-link", remote: true %></li>
        <% end %>
        <li><%= link_to "About", about_path, class: "about-link", remote: true %></li>
        <% if current_user %>
          <li><%= link_to "Sign out", destroy_user_session_path, method: "delete" %></li>
          <% else %>
          <li><%= link_to "Login", new_user_session_path, class: "signin-link", remote: true  %></li>
        <% end %>
      </ul>
    </div>
</nav>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/_about.html.erb
<div class="about">
  <h2>What is Movie Lovers?</h2>
  <p>There are millions of songs on Spotify. Play your favorites, discover
    new tracks, and build the perfect collection.
  </p>
  <h2>Movies & Friends</h2>
  <p>You’ll find readymade playlists to match your mood, put together by
    music fans and experts.
  </p>
</div>

app/views/welcome/about.js.erb
$('#front').html("<%= j (render 'about') %>").hide().fadeIn();

app/views/welcome/index.html.erb
<div class="container border">
  <div class="row">
    <div class="col-md-6">
      <h2 class="title">Your Invited...</h2>
      <h5>Discover new movies, rated and reviews by your friends and family</h5>
    </div>
    <div class="col-md-6">
      <div id="front">
      </div>
    </div>
</div>